// <auto-generated />
using KuyumcuStokTakip.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace KuyumcuStokTakip.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250611072501_RenamePartnerColumns")]
    partial class RenamePartnerColumns
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Method intentionally left empty since this migration renames columns only.
        }
    }
}
