// <auto-generated />
using KuyumcuStokTakip.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace KuyumcuStokTakip.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250713130900_AddWastageReason")]
    partial class AddWastageReason
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
