version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: kuyumcu-sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "123A.a321"
      ACCEPT_EULA: "Y"
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data:
